# Generated by Django 3.2.6 on 2021-08-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('quantity', models.IntegerField()),
                ('measure', models.CharField(max_length=12)),
                ('unit_price', models.FloatField(max_length=7)),
                ('value', models.FloatField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_base', models.FloatField(max_length=10)),
                ('tax_rate', models.FloatField(max_length=10)),
                ('payment_amount', models.FloatField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('company_id', models.IntegerField()),
                ('place', models.CharField(max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_generator.product')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_generator.tax')),
            ],
        ),
    ]
