# Generated by Django 3.2.6 on 2021-08-28 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='invoice_generator.invoice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='value',
            field=models.FloatField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax', to='invoice_generator.invoice'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='payment_amount',
            field=models.FloatField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_base',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_rate',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
