# Generated by Django 3.2.6 on 2021-08-28 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0002_auto_20210828_0559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='number',
            new_name='invoice_num',
        ),
    ]
